version: '3.7'

services:
  frontend:
    container_name: frontend
    build: .
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '5173:5173'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
